### ISSUE TITLE
How to use it in org-babel blocks ?

### ISSUE THREAD

**Issue by nanounanue** [purcell/inheritenv#4]
Hi,

I am using `envrc` package for setting the environment in the emacs buffer, using `direnv`. Everything works as expected. But if I create an org-babel block, the environment is not set properly.

Reading your README, it seems that thios package would help, but I am getting the same error as before. Do I understand correctly? Or I need to add some extra configuration?

Thanks in advance

**Comment by purcell** [comment]
I don't know much about how org-babel works, but yes, if you're having issues then it's likely that this package would help. The best option overall would be to report it as an org bug, because the org maintainers could add code similar to the code in `inheritenv` to make it work. Alternatively, you *may* be able to use this package to work around it in your user config, not really sure about that, though.

If org-babel backends are responsible for managing processes and their environments, then you might find that the issue lies with a specific backend, and not `org-babel` itself. The same approach outlined above would then apply to that backend.

**Comment by nanounanue** [comment]
Thank you for your advise.

I will report this as a org issue.

**Comment by dschrempf** [comment]
FYI: I had the same problem. There is a fix, but it is quite verbose. See https://orgmode.org/list/676F013F-AC22-4853-9E13-C91B92C3B59A@health.ucsd.edu/.

**Comment by purcell** [comment]
Awww, yes, that's not a very nice workaround.
